# Generated by Django 2.1.3 on 2019-01-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
