# Generated by Django 2.1.5 on 2019-01-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaApp', '0003_auto_20190109_0749'),
        ('pizzeriaApp', '0002_auto_20190109_0129'),
    ]

    operations = [
    ]
